### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by tekkamanmaverick** [dnelson86/ArepoVTK#3]
Hi Dylan,

I can't build the libarepo.a and get the error:
Makefile.systype: No such file or directory

Could you tell me how to fix it?

Thank you and best wishes.

**Comment by dnelson** [comment]
Hello,

This is meant to be a file containing a definition for a `SYSTYPE` variable (which can also be specified as an environment variable), telling the Makefile how to compile AREPO.

This isn't needed really for ArepoVTK.

Probably just `cp Template-Makefile.systype Makefile.systype` will work (i.e. create this file, and leave it alone).

**Comment by tekkamanmaverick** [comment]
Thank you.
However, I still can't install this software. Maybe there is something wrong with libpng. The error message is as follows，

> mpicxx -Wall -g -m64 -O3  -DH5_USE_16_API -I/include -I/include -I./libpng/ build/ArepoRT.o build/camera.o build/fileio.o build/fileio_img.o build/geometry.o build/integrator.o build/keyframe.o build/renderer.o build/sampler.o build/transfer.o build/transform.o build/util.o build/volume.o build/snapio.o build/arepo.o build/arepoTree.o build/arepoInterp.o build/voronoi_3db.o  -o ArepoRT -fopenmp -lm -L ./arepo/  -L/lib -L/lib -L./libpng/ -lgsl -lgslcblas -lgmp -lhdf5 -pthread -larepo -lpng16
/usr/bin/ld: cannot find -lpng16
/usr/bin/ld: skipping incompatible /lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /lib/librt.so when searching for -lrt
/usr/bin/ld: skipping incompatible /lib/librt.so when searching for -lrt
/usr/bin/ld: skipping incompatible /lib/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /lib/libpthread.so when searching for -lpthread
collect2: error: ld returned 1 exit status
make: *** [ArepoRT] Error 1

I did install libpng in your way.

**Comment by dnelson** [comment]
If libpng is installed, then you need to tell the linker where to find it (e.g. with a -L option). You can get some tips on such error messages by googling.
