### ISSUE TITLE
Light cone visualization

### ISSUE THREAD

**Issue by tekkamanmaverick** [dnelson86/ArepoVTK#4]
Hi Dylan,

Do you have a good strategy for visualizing the parameters along a line-of-sight? I have stacked a lot of snapshots. However, I can't load all the data into the memory.

Thank you.

**Comment by dnelson** [comment]
Hello,

You could try to pretend that the data you have made resembles a normal snapshot. But, there is no support in ArepoVTK for visualizing lightcone-like data. I would suggest in this case you try a simpler rendering.
