### ISSUE TITLE
undefined reference to symbol '__gmpz_init'

### ISSUE THREAD

**Issue by justmarvinn** [dnelson86/ArepoVTK#5]
Hello,
I followed the README instructions and there were problems with building ArepoVTK.
Makefile generates the next command:
`mpicxx -Wall -g -m64 -O3  -DH5_USE_16_API -I/include -I/include -I./libpng/ build/ArepoRT.o build/camera.o build/fileio.o build/fileio_img.o build/geometry.o build/integrator.o build/keyframe.o build/renderer.o build/sampler.o build/transfer.o build/transform.o build/util.o build/volume.o build/snapio.o build/arepo.o build/arepoTree.o build/arepoInterp.o build/voronoi_3db.o  -o ArepoRT -fopenmp -lm -L ./arepo/  -L/lib -L/lib -L./libpng/ -lgsl -lgslcblas -lgmp -lhdf5_serial -pthread -larepo -lpng16`
and then gives an error:
`/usr/bin/ld: ./arepo//libarepo.a(voronoi_3d.o): undefined reference to symbol '__gmpz_init'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libgmp.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:45: ArepoRT] Error 1`
PS

**Comment by justmarvinn** [comment]
PS: libarepo.a builds without any problems with the same option -lgmp and libgmp absolutely exactly installed in my system

**Comment by dnelson** [comment]
Perhaps [this stackoverflow](https://stackoverflow.com/questions/19901934/libpthread-so-0-error-adding-symbols-dso-missing-from-command-line) is relevant?

**Comment by justmarvinn** [comment]
No, I tried everything with compiler flags. I don't understand why arepo successfully compiles with the exactly same lib gmp

**Comment by dnelson** [comment]
That is strange - ArepoVTK does not actually need gmp, it just needs to link against libarepo.a (which does).

Maybe try putting the `-lgmp` after the `-larepo` (or a similarly trivial change). Since I've never seen this message myself, I don't think I would be able to reproduce the problem on any system I have access to.

**Comment by justmarvinn** [comment]
thank you so much, I replaced string in Makefile from
`LIBS += -lgsl -lgslcblas -lgmp -lhdf5 -pthread -larepo -lpng16 #-lhwloc`
to
`LIBS += -larepo -lgsl -lgslcblas -lgmp -lhdf5 -pthread -lpng16 #-lhwloc`
and it started working
